### ISSUE TITLE
UTF-8 error: trannergy-mqtt.trannergy_tcpclient

### ISSUE THREAD

**Issue by janwbouma** [hansij66/trannergy2mqtt#1]
Thanks for this component.
I receive the statistics from my Trannergy inverter succesfully.

Unfortunately I received the following error.

trannergy-mqtt.trannergy_tcpclient WARNING: FUNCTION:run LINE:178: Exception 'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte

Any Idea how I can fix this?

**Comment by hansij66** [comment]
Hoi Jan Willem

Sorry, no idea what the cause is; which inverter do you have; I am using
pvl5400

Maybe your inverter does not use utf8 coding

You can try to change

serial = str(rawdata[15:31], encoding="UTF-8")


to eg "ISO-8859-1"

On which OS are your running this?
Which python version?

Groet
Hans

**Comment by janwbouma** [comment]
Hi Hans,

Thanks for your response.
I get the total of produced KWH through to mqtt in Home Assistant. Works great!

I have a PVL4000.

I made the adjustment to "ISO-8859-1". Let's see tomorrow if it works tomorrow without any encoding errors.

I have dockerized the script with python 3.9 base container and run it in a docker on a Synology.
When the inverter is not available the container stops unexpectedly. maybe due to the connection errors. I bypass container stops at this moment with an auto restart of the container.

**Comment by kipusoep** [comment]
@janwbouma can you share the docker image?

**Comment by kipusoep** [comment]
@janwbouma nobody home? :-(
I had to change the encoding as well btw.

**Comment by kipusoep** [comment]
So for anyone interested, I created my own dockerfile:


```dockerfile
FROM python:3-slim-bookworm

RUN apt-get update && apt-get install git -y
RUN pip install setuptools
RUN pip install -v "paho-mqtt==1.6.1"

WORKDIR /app
RUN git clone https://github.com/hansij66/trannergy2mqtt.git .
ADD config.py trannergy_tcpclient.py .
ENTRYPOINT ["python", "trannergy-mqtt.py"] 
```
