### ISSUE TITLE
Meedere instanties

### ISSUE THREAD

**Issue by Calimerorulez** [hansij66/trannergy2mqtt#2]
Hi Hans,

Dank voor het maken van deze tool. Ik heb een huis gekocht met vier Trannergy inverters. Ik heb de eerst nu aan de praat, en voor de overige drie heb ik drie kopieën van deze tool gemaakt met bijbehorende systemd daemons, en in het betreffende python script heb ik de listen poort uniek gemaakt voor elk. 
In MQTT verschijnen de inverters correct, maar de autodiscovery in HA werkt niet lekker, omdat ik dan meerdere sensoren met dezelfde naam dreig te krijgen.

Weet jij een eenvoudige oplossing?

Hartelijk dank,
Patrick

**Comment by hansij66** [comment]
Hoi Patrick, ik heb in een andere situatie al eens gemerkt dat HA er niet
tegen kan dat er 2 sensoren zijn met dezelfde naam...m.i. een onnodige
beperking in HA, maar het is zo. Ik heb geen snelle oplossing...behalve 4
kopieen laten draaien en zorgen dat de sensoren in HA allemaal een unieke
naam krijgen.
In trannergy_parser.py kun je dat doen...maar dan moet je daar 4 versies
van maken. Lelijk....maar het is zo.

Je kunt een issue aanmaken om meerdere trannergies te supporten....als ik
me een keer verveel....maar dat gaat voorlopig niet gebeuren :)

Groet
Hans

**Comment by Calimerorulez** [comment]
Hoi Hans.
Dank je voor de tips, dan weet ik waar ik moet zoeken 😄 
Ik zal eens kijken hoe ver ik kom.

Groeten,
Patrick
